### ISSUE TITLE
Option g:snippets_dir is ignored

### ISSUE THREAD

**Issue by bogdan** [garbas/vim-snipmate#12]
When I switched to your fork I've noticed that `g:snippets_dir` is ignored. 
I actually  don't see where it's used in the code.

I don't like the default snippets and have my own collection, but I can not exclude default snippets from runtime path.

How can I ignore snippets bundled with plugin?

**Comment by vrkansagara** [comment]
> After some experiments I've solved the problem with this config:
> 
> ```
> let g:snipMate = {}
> let g:snipMate['snippet_dirs'] = funcref#Function('return ["~/.vim/snippets"]')
> ```
> 
> Not really beautiful but works.
> 
> Thanks,

I found how to work with this, you can follow https://github.com/honza/vim-snipmate/commit/581a4d1c0696bc79f461275957d5ade79624c4b8#commitcomment-48874436
