### ISSUE TITLE
snipMate is crashing Vim

### ISSUE THREAD

**Issue by Netherdrake** [garbas/vim-snipmate#126]
Hello,

I am on OSX ML, Vim 7.3. Here are my Vundles:
set nocompatible
set encoding=utf-8

" start vundler
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
filetype plugin indent on

" vim vundles
Bundle "gmarik/vundle"
Bundle "kien/ctrlp.vim"
Bundle "scrooloose/nerdtree"
Bundle "vim-scripts/taglist.vim"
Bundle "tpope/vim-fugitive"
Bundle "Lokaltog/vim-easymotion"
Bundle "nathanaelkane/vim-indent-guides"
Bundle "Lokaltog/vim-powerline"
Bundle "editorconfig/editorconfig-vim"
Bundle "mileszs/ack.vim"
Bundle "edsono/vim-matchit"
Bundle "corntrace/bufexplorer"
Bundle "sjl/gundo.vim"
Bundle "henrik/vim-indexed-search"
Bundle "flazz/vim-colorschemes"

" convenience tools
Bundle "ervandew/supertab"
Bundle "vim-scripts/tComment"
Bundle "tpope/vim-surround"

" language vundles
Bundle "pangloss/vim-javascript"
Bundle "vim-ruby/vim-ruby"
Bundle "tpope/vim-rails"
Bundle "duskhacker/sweet-rspec-vim"
Bundle "fsouza/go.vim"
Bundle "nsf/gocode"
Bundle 'Blackrush/vim-gocode'

" experimental vundles
" Bundle "Lokaltog/powerline"

" obsolete vundles
Bundle "wincent/Command-T"
Bundle "tpope/vim-pathogen"

" " snipMate with dependencies
" Bundle "MarcWeber/vim-addon-mw-utils"
" Bundle "tomtom/tlib_vim"
" Bundle "garbas/vim-snipmate"
" Bundle "honza/vim-snippets"

When I try to start Vim I get this:
`Error detected while processing /Users/jan/.vim/bundle/vim-snipmate/plugin/snipMate.vim:
line   33:
E121: Undefined variable: snippets_dir
E116: Invalid arguments for function empty(snippets_dir)
E15: Invalid expression: empty(snippets_dir)
line   37:
E121: Undefined variable: snippets_dir
Press ENTER or type command to continue`

Also whenever I try to open any buffer in Vim, I get this error:
`Error detected while processing FileType Auto commands for "*":
E121: Undefined variable: snippets_dir
E116: Invalid arguments for function GetSnippets`

If I disable snipMate, Vim is fine. Any ideas how to fix this? I'd really love to use this plugin.

**Comment by zeka0** [comment]
Thanks a great lot. The distribution on vim official site is year-2009-version, may be they should update right now...
