### ISSUE TITLE
Backspace ends tab jumping

### ISSUE THREAD

**Issue by jtrussell** [garbas/vim-snipmate#159]
Suppose I have a snippet defined like so:

```
snippet f
    function(${1:/*args*/}) {
      ${3:/*code*/}
    }${2:;}
```

I type `f<tab>` and the snippet expands with `/*args*/` highlighted as expected. I can type something out like `foobar` then tab to $2 but if I just hit the backspace key my tab chain is broken (i.e. hitting tab at that point does nothing).

Any thoughts? I've tried with all other non-required plugins removed and a minimal vimrc:

``` viml
set nocompatible
filetype plugin indent on
syntax on

runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
```

**Comment by stephenpcook** [comment]
If I'm using a snippet
```
snippet foo
        function foo${1:bar} {
                ${2}
        };
```
and I want
```
function foo {
        bat
};
```
it seems I have to type `foo<TAB><BS><ESC>i<TAB>bat`, as `foo<TAB><BS>` leaves me unable to tab to the next snippet point, with the `<ESC>i` being the work around discussed above (if I've understood correctly).

In older versions of [snipMate](https://github.com/vim-scripts/snipMate) I could achieve this with `foo<TAB><BS><TAB>bat`. Would it be possible to have this functionality?

**Comment by ajzafar** [comment]
@stephenpcook That's very possible with a mapping. I personally use

    smap <BS> x<BS><Plug>snipMateNextOrTrigger

This deletes the text of the current stop and goes to the next one. The mapping SnipMate used to use should still be usable too, if you want that.
