### ISSUE TITLE
single buffer triggers alt-file error on '#' char snippet

### ISSUE THREAD

**Issue by fourjay** [garbas/vim-snipmate#183]
Opening a new file (perl/sh tested) without an alternate file, and using the shebang snippet triggers a string of alt-files errors. But opening a file, then opening a new or existing file, the shebang snippet works.

I've tested this with a minimal snipmate install with Vundle, basically the Vundle setup and
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'

(sample) of errors (it repeats)
Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor..funcref#Call..snipMate#GetSnippets..funcref#Call..snipMa
te#DefaultPool:                                                                                                                                                   
line   13:                                                                                                                                                        
E194: No alternate file name to substitute for '#': runtime! snippets/perl.snippets snippets/perl_*.snippets snippets/perl/*.snippets snippets/perl/#!*.snippet sn
ippets/perl/#!*/*.snippet                                                                                                                                         
Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor..funcref#Call..snipMate#GetSnippets..funcref#Call..snipMa
te#DefaultPool:                                                                                                                                                   
line   13:                                                                                                                                                        
E194: No alternate file name to substitute for '#': runtime! snippets/_.snippets snippets/__*.snippets snippets/_/*.snippets snippets/_/#!*.snippet snippets/_/#!*
/*.snippet                                                                                                                                                        
Error detected while processing function snipMate#ShowAvailableSnips..snipMate#GetSnippetsForWordBelowCursorForComplete..snipMate#GetSnippetsForWordBelowCursor..f
uncref#Call..snipMate#GetSnippets..funcref#Call..snipMate#DefaultPool:

**Comment by ajzafar** [comment]
I just pushed a fix. Let me know how it works. Thanks for the report!

**Comment by fourjay** [comment]
It works! Thanks! And thanks for the update, I'm happy about nesting :-)

**Comment by ajzafar** [comment]
Glad to hear it!
