### ISSUE TITLE
Errors with POSIX shell variables

### ISSUE THREAD

**Issue by yann-morin-1998** [garbas/vim-snipmate#184]
Hello!

And here I'm back with yet another brokenness when pressin TAB after a POSIX variable rerference:

    echo "${foo#*/}"

Press TAB when the cursor is just at the end of the line:

    Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor..funcref#Call..snipMate#GetSnippets
    ..funcref#Call..snipMate#DefaultPool:
    line   13:
    =snipMate#ShowAvailableSnips()
    Error detected while processing function snipMate#ShowAvailableSnips..snipMate#GetSnippetsForWordBelowCursorForComplete..snipMate#    GetSnippetsForWordBelowCursor..funcref#Call..snipMate#GetSnippets..funcref#Call..snipMate#DefaultPool:
    line   13:
    E194: No alternate file name to substitute for '#': runtime! snippets/_.snippets snippets/__*.snippets snippets/_/*.snippets snippets/_/foo#\*/\}

Regards,
Yann E. MORIN.

**Comment by ajzafar** [comment]
This looks a bit like #183 fixed earlier today. Can you pull from master again and see if the problem persists?

**Comment by yann-morin-1998** [comment]
Indeed, I was not up-to-date, and missed #183 because it was closed.

It works with current master, thanks!

Closing. :-)
