### ISSUE TITLE
Equivalent for "snippets" folder?

### ISSUE THREAD

**Issue by llinfeng** [garbas/vim-snipmate#186]
`FileType.snippets` used to have been stored in a folder called `snippets`. This makes snippets highly customizable. I forked from this branch 8 months ago but now, everything had changed!

May I customize the snippets in the old way? Where should I go then to customize the snippets? Or, could you please point me to the help-file, if exists?

Thank you!

**Comment by ajzafar** [comment]
That hasn't changed at all. SnipMate still looks for a folder named `snippets` in every folder in your `'runtimepath'`. Creating your own snippets is detailed in [the `:h SnipMate-snippets` section of the help](https://github.com/garbas/vim-snipmate/blob/master/doc/SnipMate.txt#L209). That is, on a Unix system, you can create a folder `~/.vim/snippets` and store your personal snippets in there. Forking SnipMate to edit the snippets it used to ship was in fact never required.
