### ISSUE TITLE
Expand dot in C snippet. 

### ISSUE THREAD

**Issue by grisuthedragon** [garbas/vim-snipmate#190]
I am using the snipmate in my vim to program C. After a long time I did an update to current version from this git repository. But from this moment on, one of my favorite C snippets does not work correctly anymore. I use the dot . to generate the array access [ ] using this snippet:
    snippet .
         [${1}] ${2}

If type 
   test<Space>.<Tab> 
it works but if I use
   test.<Tab>

I get the tab as whitespace. But I think the old behavior, that it works in both cases, would be at least useful to turn it on using an option.

**Comment by ajzafar** [comment]
I just pushed a fix for this. Thanks for the report!
