### ISSUE TITLE
SnipMateOpenSnippetFiles index not pointing to the right file

### ISSUE THREAD

**Issue by ddaza** [garbas/vim-snipmate#194]
The OpenSnippetFiles function uses the tlib#input#List function but it might be returning the wrong index. 

When pointing to index 01 it opens 02 and when pointing to 02 it opens 03. If 03 is not found it aborts and fails.  This can very well be a tlib issue or the way you loop though the selected files.

Just for reference I have this plugins installed

```
ack.vim
supertab
tlib_vim
vim-addon-mw-utils
vim-airline
vim-easymotion
vim-jade
vim-less
vim-snipmate
vim-snippets
vim-surround
vim-tabber
```

At least this is what I am seeing in my vim.

**Comment by ajzafar** [comment]
It looks like the `-1` was lost in d704f34. It's fixed now. Thanks for the report!
