### ISSUE TITLE
Broken docs for snippet_dirs, additional locations

### ISSUE THREAD

**Issue by Jack12816** [garbas/vim-snipmate#198]
The [broken docs](https://github.com/garbas/vim-snipmate/blob/master/doc/SnipMate.txt#L440) show a example which does not work anymore. This seems to be a bug if we trust [the comment](https://github.com/garbas/vim-snipmate/blob/master/plugin/snipMate.vim#L93). Because a functionref will not work anymore.

Could you please correct this? :)

**Comment by ajzafar** [comment]
Thanks for pointing that out! It's fixed now.

If I may ask, assuming you were trying to use a funcref, what was your function going to do? I have some ideas on how to improve that part of SnipMate, but any input is welcome. I'm hoping to start working on it after releasing a new version. That should happen in the next week. (I will open a separate issue for more discussion at that time.)

**Comment by Jack12816** [comment]
I was using it to add additional locations for snippets on my $HOME. Here is a [example](http://code.jity.de/Jack12816/linux-environment/blob/master/dotrc/.vim/vimrc/bundles-options.vim#L271-272) how I used it. It would be great to just push new locations for snippets. :)

Setting a list is good as well. But I hope the entries on the list will be pushed to the default locations. So this setting should not be destructive I think.

**Comment by ajzafar** [comment]
I think that adding the default directories to the list specified by the user is reasonable. However, this option has always functioned the way it does now, and I don't think I want to mess with that at this moment, in the case that someone preferred the current behavior. It's fairly simple to add the defaults to your list though:
````vim
let g:snipMate.snippet_dirs = split(&rtp, ',') + [ $HOME . "/.bashrc.d/vim" ]
````
Thanks for your input nonetheless!

**Comment by Jack12816** [comment]
Ah ok - thank you for the hint! :)
