### ISSUE TITLE
SnipMate not working on <tab>

### ISSUE THREAD

**Issue by zachschultz** [garbas/vim-snipmate#200]
I have snipMate installed along with snippets, using Pathogen, however whenever I try to run a snippet nothing happens.

I do have SuperTab installed, would that be causing any problems with snipMate?

**Comment by ajzafar** [comment]
SnipMate and SuperTab should cooperate alright, so it's probably not that. Could you try the checklist in the README please? In particular, make sure that your trigger key (tab by default) is mapped correctly with, for example, `:imap <tab>`.

**Comment by zachschultz** [comment]
The output I get from `:imap <tab>` is: 

`<Tab>                       <Plug>SuperTabForward`

Looks like it's not mapped correctly. Regarding the install, I followed every instruction, but I'll look at the README checklist again.

**Comment by zachschultz** [comment]
The output I get from `:imap <tab>` is: 

`<Tab>                       <Plug>SuperTabForward`

Looks like it's not mapped correctly. Regarding the install, I followed every instruction, but I'll look at the README checklist again.

**Comment by ajzafar** [comment]
Could you share the output of `:scriptnames` please?

**Comment by ajzafar** [comment]
@zachschultz ping

**Comment by zachschultz** [comment]
Hey @ajzafar sorry, I solved the problem with a reinstall of `vim-snipmate`. I believe I may have had the directory in a different location for some reason.

**Comment by ajzafar** [comment]
Alright then, I'm going to close this.
