### ISSUE TITLE
Can no longer select completions [glob]?

### ISSUE THREAD

**Issue by dylansm** [garbas/vim-snipmate#202]
<C-N> and <C-P> no longer work for me. For example, if I'm in a Ruby file and type mod<tab> I get the following:
_______________________________________________
<my_actions.rb [+]
  1 1* 1. ruby borg/.vim module .. ClassMethods .. end
  2 2: 2. ruby borg/.vim module .. module_function .. end
  3 3: 3. ruby borg/.vim module .. end
__InputList__
select snippet by name (filter: ; press <F1> for help)  [glob]
_______________________________________________

Why am I suddenly having to select by name instead of number? Thanks.

**Comment by ajzafar** [comment]
@dylansm I'm afraid I can't reproduce this. Using the same `mod` snippets from your dotfiles repo, I can use numbers just fine to determine which snippet to expand. Can you please make sure you're up to date with both SnipMate and tlib? I'm really not sure what the problem might be.

**Comment by dylansm** [comment]
Thanks for getting back to me. I am all up to date. It still works, but not the numbers. I have to filter down the list by typing a name and then press enter—it's like some kind of input_list filter mode or something.

**Comment by ajzafar** [comment]
Hmm my first guess is that there's some Vim setting or plugin you're using that either SnipMate or tlib (the library providing the selection code) isn't adequately handling. Can you start Vim without anything then see how it works? Start Vim with `vim -N -u NONE` then enter these commands:

    :set rtp+=~/.vim/bundle/tlib
    :runtime! plugin/**/*tlib*.vim
    :call tlib#input#List('si', 'select one', ['1. foo', '2. bar', '3. baz'])

Replace the path to tlib as needed in the first command of course. See if you can use numbers to select one of the options. If it does work, can you share your vimrc and a list of plugins you use? We can work from there.

**Comment by ajzafar** [comment]
@dylansm ping

**Comment by dylansm** [comment]
Thanks for the ping. First, I didn't ever have a separate tlib installed, and it always seemed to work. I installed tlib_vim and ran though the commands you gave. On the third command I got:

    E117: Unknown function: tlib#input#List

Thoughts?

**Comment by ajzafar** [comment]
Hmm did you replace the path to tlib to whatever your path to tlib is in the first command? If you use the wrong path, it won't let you know until the third command.

I'm not sure what you had that allowed SnipMate to work. While SnipMate only uses tlib in a couple places, the very situation resulting in this issue is one of them. The whole menu that comes up for choosing snippets is provided by the tlib function `tlib#input#List`.

**Comment by dylansm** [comment]
Looks like there are two different libraries:
https://github.com/vim-scripts/tlib and
https://github.com/tomtom/tlib_vim

I have the first — maybe I should install the second instead?

**Comment by ajzafar** [comment]
Those two should be the same library. The tomtom one is more likely to be up to date though as that's the authoritative repo from the author. The vim-scripts repo is only updated when the plugin on vim.org is updated.

**Comment by dylansm** [comment]
I moved the directory to .vim/bundle/tlib and all three commands worked perfectly.

**Comment by dylansm** [comment]
It's definitely some tlib glob setting. I'm looking at the tlib docs now.

**Comment by ajzafar** [comment]
Can you share your vimrc?

**Comment by dylansm** [comment]
Let's close this. I really appreciate your attention and effort. I seem to be an outlier. I've switched over to UltiSnips — with that I can trade three dependencies for one, as well. Thank you.
