### ISSUE TITLE
Multi-line snippets doesn't work

### ISSUE THREAD

**Issue by dreviejo** [garbas/vim-snipmate#206]
After pattern change in autoload/snipmate/legacy.vim for issue #203, when using snippets with several lines/tags, it works with the first line, but not with any jump afterwards: the cursor go to a wrong place and visual marking the wrong text.
Maybe is a bug in my vim version (Vim 7.4.712), but your new pattern ('\\\_^.*\ze'...) seems to match always from the start of the string. I did try with '\\\_^.\\{-}\ze'... to get the shortest match, but it didn't work either.
My alternative is to use '[^\n]\\{-}\ze'..., matching the shortest prefix not including new lines.

This is the patch:
```
diff --git a/autoload/snipmate/legacy.vim b/autoload/snipmate/legacy.vim
index c4d0a0b..b4ea8a5 100644
--- a/autoload/snipmate/legacy.vim
+++ b/autoload/snipmate/legacy.vim
@@ -87,7 +87,7 @@ function! snipmate#legacy#build_stops(snip, lnum, col, indent) abort
 
 		let stops[i] = {}
 		let stops[i].line = a:lnum + s:count(beforeTabStop, "\n")
-		let stops[i].col = a:indent + len(matchstr(withoutOthers, '\_^.*\ze'.s:sigil .'{'.i.'\D'))
+		let stops[i].col = a:indent + len(matchstr(withoutOthers, '[^\n]\{-}\ze'. s:sigil .'{'.i.'\D'))
 		let stops[i].placeholder = 0
 		let stops[i].mirrors = []
 		if stops[i].line == a:lnum
```

**Comment by ajzafar** [comment]
Thanks for the fix! Merged.
