### ISSUE TITLE
javascript snippets issue

### ISSUE THREAD

**Issue by unclechu** [garbas/vim-snipmate#208]
For example I have snippet:
```text
snippet ::
        .prototype.
```
When I type this:
```javascript
bar::
```
End press snippet key, it transforms to:
```javascript
bar.prototype.
```
But if I type this:
```javascript
foo.bar::
```
Snippet key doesn't work, it just added \t:
```javascript
foo.bar::>---
```

**Comment by ajzafar** [comment]
This should be fixed in e2d294b. Let me know how it works.

**Comment by unclechu** [comment]
@ajzafar now it works correct! Thanks a lot!

**Comment by unclechu** [comment]
Here the example of code that I need to write:
```javascript
SocialSubFieldsCollection.__super__.initialize.apply(this, arguments);
```
I try to write:
```javascript
SocialSubFieldsCollection.__super__.initialize.ap
```
Here the snippet: https://github.com/unclechu/vimrc2/blob/master/.vim/snippets/javascript.snippets#L104-L105
When I have space before `.ap` it calls snippet-autocomplete, but in this keys it doesn't. But still works when I type full snippet name `.apply`.

**Comment by ajzafar** [comment]
@unclechu I am going to open a new issue for that.
