### ISSUE TITLE
Error detected while processing function snipMate#TriggerSnippet

### ISSUE THREAD

**Issue by eytanrs** [garbas/vim-snipmate#210]
I was able to run snipmate with no problem in my other computer. However when I installed it to my new mac its giving me the following error.

Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor..funcref#Call..snipMate#GetSnippets..funcref#Call..snipMate#DefaultPool:
line   12:
E714: List required

Here is my runtime path:
runtimepath=~/.vim/bundle/vim-snippets/after/plugin,~/.vim,~/.vim/bundle/ctrlp.vim,~/.vim/bundle/git-grep-vim,~/.vim/bundle/nerdcommenter,~/.vim/bundle/play,~/.vim/bundle/tlib_
vim,~/.vim/bundle/vim-addon-mw-utils,~/.vim/bundle/vim-autoformat-master,~/.vim/bundle/vim-bundler,~/.vim/bundle/vim-git-grep-rails-partial,~/.vim/bundle/vim-rails,~/.vim/bundle/
vim-snipmate,~/.vim/bundle/vim-snippets,~/.vim/bundle/vim-surround,/usr/share/vim/vimfiles,/usr/share/vim/vim73,/usr/share/vim/vimfiles/after,~/.vim/bundle/vim-snipmate/after,~/.vim/after,~/.vim/eclim,~/.vim/eclim/after

I'm not sure what's wrong.

**Comment by MarcWeber** [comment]
Try this: :debug echo snipMate#DefaultPool() which may help finding the
issue (also have a look at the code of that function).

**Comment by eytanrs** [comment]
E119: Not enough arguments for function: snipMate#DefaultPool
E15: Invalid expression: snipMate#DefaultPool()

**Comment by ajzafar** [comment]
@eytanrs Are you running the latest master? Can you share the output of the command `:echo string(g:snipMate.snippet_dirs)`? Are you setting it in your vimrc or elsewhere? If you are, it must be a list. SnipMate should output a message if it detects that the variable isn't a list.

**Comment by eytanfb** [comment]
This is the result for `:echo g:snipMate`:

`{'get_snippets': {'faked_function_reference': 'snipMate#GetSnippets'}, 'snippet_dirs': '~/.vim/bundle/vim-snippets/snippets', 'no_match_completion_feedkeys_chars': '   ', 'get_sc
opes': {'faked_function_reference': 'return split(&ft,"\\.")+[&syntax, "_"]'}, 'scope_aliases': {'xhtml': 'html', 'scss': 'css', 'ur': 'html,javascript', 'cu': 'c', 'less': 'css'
, 'php': 'php,html,javascript', 'html': 'javascript', 'objc': 'c', 'cpp': 'c', 'mxml': 'actionscript', 'eruby': 'eruby-rails,html'}}`

This is the result for `:echo string(g:snipMate.snippet_dirs)`:
`'~/.vim/bundle/vim-snippets/snippets'`

**Comment by ajzafar** [comment]
@eytanfb That would be the problem. It looks like your `g:snipMate.snippet_dirs` is a string when it should be a list. Are you setting it in your vimrc? If so, make sure to make it a list, e.g.,

    let g:snipMate.snippet_dirs = [ '~/.vim/bundle/vim-snippets/snippets' ]

Again SnipMate should be giving you a message about this if you're up to date.

**Comment by eytanrs** [comment]
I actually copied over my .vimrc and my .vim from my other computer and everything is working now. but i'm still not sure what the issue was
