### ISSUE TITLE
load specific snippets for file types

### ISSUE THREAD

**Issue by ddaza** [garbas/vim-snipmate#211]
It's been a year since the #169. Is there an easy solution for this? I am surprised more people are not reporting this. 

``` vim
let g:snipMate = {}
let g:snipMate.scope_aliases = {}
let g:snipMate.scope_aliases['javascript'] ='javascript,javascript-requirejs,javascript.node'
```

still load everything in the `javascript/` folder

```
.
├── javascript.d3.snippets
├── javascript-jquery.snippets
├── javascript.node.snippets
├── javascript-requirejs.snippets
└── javascript.snippets
```

Thanks!

**Comment by ajzafar** [comment]
If I understand your file layout correctly, this is working as intended. As described in `:h SnipMate-snippets`, for the `javascript` scope, files within `snippets/javascript/` will be loaded. If you don't want, say, `javascript-jquery.snippets` to be loaded, it should be in the upper `snippets/` directory. This is meant to mirror Vim's naming scheme for ftplugins (see `:h ftplugin-name`; I believe this is used for `indent` and `syntax` files as well, but I'm not sure). Maybe this structure doesn't make sense for snippets. I am open to hearing arguments in favor of changing this, but as it stands at the moment, I prefer to follow the choices Vim made.
