### ISSUE TITLE
snippet doesn't work as expected

### ISSUE THREAD

**Issue by SukumarMehta** [garbas/vim-snipmate#212]
```
snippet {
  ${1:function}:{[${2:arguments}]
    ${3:body}
    }
```

The first 2 tabstops work fine, but the 3rd stop highlights the '}' end-brace instead of the 'body' text

I've tried changing $3 to $0 to no avail.

Please advise

![snippet issue](https://cloud.githubusercontent.com/assets/8241601/10499072/420c3a22-729c-11e5-8e20-7dc54dc40acb.PNG)

**Comment by ajzafar** [comment]
@SukumarMehta I'm unable to reproduce this on master. Can you make sure you're on master as well? If you're still getting that behavior on master, does it still happen if you rename the trigger to something simple like `foo`? If you move the snippet to another filetype, does this misbehavior still happen? Does it happen with both versions of the snippet parser (see `g:snipMate.snippet_version` in `:h SnipMate-options`)? What Vim version are you using? Can you supply a minimalist vimrc that reproduces this?

**Comment by SukumarMehta** [comment]
```
let g:snipMate={}
let g:snipMate.snippet_version=1
```
That did the trick - thanks!

Question: is there some documentation that details the motivation behind the 2 versions and what's different about them?

**Comment by ajzafar** [comment]
Version 0 is the original SnipMate parser, almost entirely as created by msanders. This parser is regex based, so it has some clear limitations, in addition to being hard to maintain. Version 1 is a proper parser, which allows for nested tabstops like `${1:foo ${2:bar}}`, and with it come some nice improvements (like `${1/foo/bar}` replacements). The differences are mentioned in the description of the snippet syntax at `:h SnipMate-syntax`.
