### ISSUE TITLE
Feature request: a way to remove or ignore snippets for a certain trigger

### ISSUE THREAD

**Issue by ajzafar** [garbas/vim-snipmate#214]
From @fvisin in #65:

> +1 I would also like this option implemented in the original snipmate.
>
> My solution for the time being is to fork https://github.com/honza/vim-snippets and remove the . snippet. The best for me would be to have an configuration option in snipmate to ignore some snippets. Do you think it could be feasible?

**Comment by ajzafar** [comment]
This is a very reasonable request. I hope to have some time this week to make it happen.

**Comment by fvisin** [comment]
That's great, thank you!

**Comment by ajzafar** [comment]
Just added support for this in 7f91de3. A line like `snippet!! foo` will remove all previously loaded `foo` snippets. Note that this means load order matters, so you may want to be removing snippets in `~/.vim/after/snippets/python.snippets` for example.

**Comment by fvisin** [comment]
Great job, thank you!
