### ISSUE TITLE
Cannot get snippets to show or work

### ISSUE THREAD

**Issue by EwanValentine** [garbas/vim-snipmate#216]
I've been trying to get snipMate working all morning, I've got the latest version installed. Had absolutely no luck. Finally I installed https://github.com/SirVer/ultisnips and it worked very briefly until I changed something in my .vimrc (shown below).

<img width="664" alt="screen shot 2015-11-13 at 13 53 39" src="https://cloud.githubusercontent.com/assets/1155123/11147461/fdcd7ffe-8a0d-11e5-91bd-5c6dd23e8742.png">

Any help greatly appreciated. I'm using MacVim on the most recent OSX.

**Comment by ajzafar** [comment]
@EwanValentine I'm going to assume you're asking for help with SnipMate, so could you go through [the checklist in the FAQ in the README](https://github.com/garbas/vim-snipmate/blob/master/README.md#faq)? It may also be best to only have one of SnipMate and UltiSnips installed at a time.

**Comment by EwanValentine** [comment]
Sorted it, thanks!
