### ISSUE TITLE
Missing tlib

### ISSUE THREAD

**Issue by janbaer** [garbas/vim-snipmate#217]
I installed vim-snipmate with the vundle plugin and of course I also installed tomtom/vimtlib' and 'MarcWeber/vim-addon-mw-utils'

But whenever I try to edit an javascript file, I get the following error message:

Error detected while processing /Users/jan/.vim/bundle/vim-snipmate/autoload/snipMate.vim:
line    9:
you're missing tlib.

Do you've any idea what the problem could be? Thanks!

**Comment by ajzafar** [comment]
Hmm I'm unable to reproduce this. Can you make sure you're on master for all three plugins: SnipMate, mw-utils, and tlib? What version of Vim are you running as well? Does this happen only for JavaScript or for other filetypes that you want to use SnipMate with as well? Can you make sure tlib is actually installed correctly and loaded too? (`:echo g:loaded_tlib` should output a nonzero number and the `:TScratch` command should open a window named `__Scratch__`.)

**Comment by gchan310** [comment]
I'm also seeing the same issues except with any filetype. I'm using VIM 7.0, (company won't update to a newer version).

I do get a non-zero number when doing (:echo g:loaded_tlib) and a command window with :TScratch

**Comment by stoptime** [comment]
I am have the same problems - Vim 7.0 on Linux. I also get a non-zero number when doing (:echo g:loaded_tlib) and a command window with :TScratch

I followed the Pathogen instructions. From what I can tell, all files/plugins are loading correctly - I have a pretty minimal setup. 

I duplicated my Vim setup on a Mac with Vim 7.3 - and it works, so seems like a version issue - if there any way to support 7.0? That's also what my company uses :\   

Many thanks for the plugin!

**Comment by ajzafar** [comment]
@janbaer @gchan310 @stoptime I pushed a possible work around to the tlib_fix branch. Could the three of you try it out and let me know if it solves the problem?

**Comment by gerases** [comment]
I also have this same problem. I will try the fix and get back.

**Comment by gerases** [comment]
That didn't seem to help. I ended up upgrading to vim 7.4.1152. The version i had was 7.0.109
