### ISSUE TITLE
How to "let g:snipMate.override=1 "

### ISSUE THREAD

**Issue by intijk** [garbas/vim-snipmate#219]
I want the override feature, after installation, I tried to do this after I start vim
let g:snipMate.override=1 
it works good, but when I add this line to .vimrc, it always bugs me with:
E121: Undefined variable: g:snipMate

I am not quite familiar with vimscript, could you tell me how to set the g:snipMate.override=1 as default option?

**Comment by ajzafar** [comment]
@intijk Sorry for the late response! The variable `g:snipMate` is a dictionary, so it needs to be created before you can set the `override` key:
````vim
let g:snipMate = {}
let g:snipMate.override = 1
````
Alternatively you can do both in one go like this:
````vim
let g:snipMate = { 'override' : 1 }
````
See `:h Dictionary` for more information.
