### ISSUE TITLE
When I hit <tab> it always show multiple snippet options.

### ISSUE THREAD

**Issue by sahibalejandro** [garbas/vim-snipmate#221]
I have these files
- `~/.vim/snippets/php.snippets`
- `~/.vim/snippets/javascript.snippets`

Both of them has a `met` snippet to expand the code for a method, but, when I'm on a `php` file and then type `met<tab>` it shows a snippets list to select php or javascript, but, it's not supposed to only expand the php snippet?

I'm missing something?

**Comment by ajzafar** [comment]
This is a result of scope aliases (see `:h SnipMate-scopes` and the `g:snipMate.scope_aliases` option under `:h SnipNMate-options`). For some scopes (`:h SnipMate-scopes`), it can make sense to include snippets from a different scope. For example include C snippets when editing a C++ file. One of the default scope aliases includes JavaScript when editing PHP files. This can be disabled by putting the following, as an example, in your vimrc:

    let g:snipMate = {}
    let g:snipMate.scope_aliases = {}
    let g:snipMate.scope_aliases.php = 'php, html'

Alternatively you can disable the default aliases entirely  by setting `g:snipMate.no_default_aliases` to 1.

I'm going to leave this open to remind me to improve the documentation on scope aliases.

**Comment by sahibalejandro** [comment]
I just use `let g:snipMate.no_default_aliases = 1` it's fine to me.
Thank you!

**Comment by sahibalejandro** [comment]
Hum... now there is another problem... when I source my `.vimrc` again file `let g:snipMate.no_default_aliases = 1` has no effect, and snippet options come back again.

**Comment by ajzafar** [comment]
@sahibalejandro See issue #220 for the fix for that.
