### ISSUE TITLE
Problem after install through pathogen

### ISSUE THREAD

**Issue by psychoslave** [garbas/vim-snipmate#225]
Just after installing with pathogen, here are the errors I get:

```
$ LANG=C vim /tmp/test.html
Error detected while processing /home/msg/.config/vim/bundle/tlib_vim/plugin/02tlib.vim:
line    9:
E492: Not an editor command: ^M
line   10:
E15: Invalid expression: &cp || exists("g:loaded_tlib")^M
line  106:
E488: Trailing characters
line  107:
E171: Missing :endif
Error detected while processing /home/msg/.config/vim/bundle/vim-snipmate/plugin/snipMate.vim:
line    9:
E492: Not an editor command: ^M
line   10:
E15: Invalid expression: exists('loaded_snips') || &cp || version < 700^M
line  138:
E171: Missing :endif
Error detected while processing /home/msg/.config/vim/bundle/vim-snippets/plugin/vimsnippets.vim:
line    1:
E15: Invalid expression: exists("b:done_vimsnippets")^M
line   51:
E171: Missing :endif
Error detected while processing /home/msg/.config/vim/bundle/vim-snipmate/after/plugin/snipMate.vim:
line    4:
E492: Not an editor command: ^M
line    5:
E15: Invalid expression: &cpo^M
line    6:
E488: Trailing characters: cpo&vim^M
line    7:
E492: Not an editor command: ^M
line    8:
E488: Trailing characters
line   14:
E492: Not an editor command: ^M
line   15:
E15: Invalid expression: !exists('g:snips_no_mappings') || !g:snips_no_mappings^M
line   47:
E171: Missing :endif
```

And then:
``"/tmp/test.html" [New File]
Error detected while processing /home/msg/.config/vim/bundle/vim-snipmate/ftplugin/html_sni
p_helper.vim:
line    2:
E15: Invalid expression: exists('s:did_snip_helper') || &cp || !exists('loaded_snips')^M
line   11:
E171: Missing :endif
`

As you can see I use  /home/msg/.config/vim/ to store every configuration file related to vim. Also my `vim` command is an alias for  `gvim -v`, if that can help.

**Comment by ajzafar** [comment]
However you obtained SnipMate, the files have carriage returns in them when they shouldn't. That's what all the `^M`s are in the errors. The following commands should fix it:

    $ cd /path/to/wherever/you/keep/snipmate
    $ vim -c 'args **/*.vim **/*.txt **/*.md | argdo s/\r// | xa'
