### ISSUE TITLE
Mirror with RegExp not working as expected

### ISSUE THREAD

**Issue by samuelsimoes** [garbas/vim-snipmate#226]
Hi, I'm trying to create a snippet that gets the mirror's first letters (mirror is snake case), like this:

````
snippet f
	FROM ${1:table_name} <only-mirrors-first-letters>
```

On Vim I can do this with this RegExp `s/\(\w\)[a-z]\+_\?/\1/g`

I tried:

```
snippet f
	FROM ${1:table_name} ${1/s/\(\w\)[a-z]\+_\?/\1/g}
```
But without success. :pensive: 

Am I doing something wrong or isn't it possible?

Thanks for your attention.

**Comment by CharlesGueunet** [comment]
Hi,

For the snippets to work well with substitution, you might need to take care how you escape parenthesis  and other selector.
For exemple take a look at this snippet ( from [here](https://github.com/GuillaumeFavelier/vim-snipmate-snippets/tree/1ab02ac2754eb8ddbc8c9cc0516e23471e6ac157) )  : 
```
snippet getvar                                                                                                                                                                                                                             
     inline const ${2:auto} get${1/\\([a-zA-Z]*\\)\\(_*\\)/\\u\\1/g}(${3:void}) ${4:const}                                                                                                                                                  
     {                                                                                                                                                                                                                                      
       return ${1:Var};                                                                                                                                                                                                                     
     }
```

Also, to make this snippets works well, I had to correct a [bug](https://github.com/garbas/vim-snipmate/pull/229) in snipmate. You can use [this patch](https://github.com/garbas/vim-snipmate/pull/229/files) to avoid the bug or use [my fork](https://github.com/CharlesGueunet/vim-snipmate/tree/312b65f756b7afbce277800dd40143ade72c7502) .

**Comment by ajzafar** [comment]
Charles is absolutely correct about what was happening. Due to oversight on my part, SnipMate was treating substitutions like everything else in a snippet, when in my opinion backslashes should be read more literally in those. They are now as of the above referenced commit. Thanks for the report!

**Comment by samuelsimoes** [comment]
Hi, with @CharlesGueunet fork and using this:

```
snippet f
	from ${1:table_name} ${1/\\(\\w\\)[a-z]\\+_\\?/\\1/g}
```

the result was accomplished, but just to point I still can't get this working with this repo's current master.

**Comment by ajzafar** [comment]
@samuelsimoes With master, you no longer need to double up on backslashes. The snippet works for me as this:

    snippet f
        FROM ${1:table_name} ${1/\(\w\)[a-z]\+_\?/\1/g}

**Comment by samuelsimoes** [comment]
@ajzafar great, it really works. I missed the point about the backslash, sorry. So, closing this issue again.

**Comment by ajzafar** [comment]
No problem! Glad it's working.
