### ISSUE TITLE
E117: Unknown function: GetSnippets

### ISSUE THREAD

**Issue by kratos6753** [garbas/vim-snipmate#228]
I recently installed vim-snipmate plugin through vundle by following the instructions given in README file, I am getting the following error when I open a file in vim

> Error detected while processing /home/chiru/.vim/bundle/snipmate.vim/after/plugin/snipMate.vim:
line   37:
E117: Unknown function: GetSnippets
Press ENTER or type command to continue

The function is  in ~/.vim/bundle/snipmate.vim/plugin/snipMate.vim, I have no idea how to call this function defined in some other file.

**Comment by ajzafar** [comment]
@kratos6753 Can you please verify that you are using an unmodified master from this repository? Currently, [that file](https://github.com/garbas/vim-snipmate/blob/master/after/plugin/snipMate.vim) does not even mention a `GetSnippets` function. I believe it's been a long time now that an unqualified `GetSnippets` function has even existed in this repo.

**Comment by kratos6753** [comment]
Thanks for you suggestion. It worked.
