### ISSUE TITLE
navigating the trigger dropdown

### ISSUE THREAD

**Issue by iandberg** [garbas/vim-snipmate#232]
Sorry if this was spelled out somewhere - I looked around and couldn't find an answer.
When hitting tab and getting multiple trigger choices in the little dropdown, are there key-cuts for moving up and down the list? Yes, I can use the arrow keys, but was looking for a more 'Vim' way of doing it. Maybe a way to map? Thanks!

Ian

**Comment by ajzafar** [comment]
That menu uses the same pop up menu that insert completion uses. Moving up/down it can be done with `<C-P>` and `<C-N>`. More info can be found at `:h ins-completion-menu` specifically the `:h popupmenu-keys` section.

**Comment by iandberg** [comment]
thanks!
