### ISSUE TITLE
Missing $0 tab stop is placed at the beginning of the last line

### ISSUE THREAD

**Issue by forkbong** [garbas/vim-snipmate#235]
For example expanding the following snippet

```
snippet snip
	test test test
	asdf asdf asdf
```

gives

```
test test test
|asdf asdf asdf
```

instead of

```
test test test
asdf asdf asdf|
```

This only happens with the new parser and the last commit that works properly seems to be 18d51dd.  So the bug must have been introduced in df5dc35 though at this commit snippets don't get expanded at all.

**Comment by ajzafar** [comment]
It was actually placing it at the beginning of the line after the snippet. How naughty. It's fixed now though! Thanks for the report!
