### ISSUE TITLE
Latex snippets are Wrong

### ISSUE THREAD

**Issue by CharlesGueunet** [garbas/vim-snipmate#236]
Hi,

This problem seems to have appeared after the change on the mirror [#226](https://github.com/garbas/vim-snipmate/issues/226).
On latex, the first '\' is ommited : 

sec<tab>  should give  \section{section name}...
and really give               section{section name}...

it makes most of the snippets unusable in latex.
Maybe some backslash needs to be kept.

Thanks for your consideration,

Charles

**Comment by ajzafar** [comment]
@CharlesGueunet The changes in #226 only affected backslashes inside of a mirror substitution context, like `${1:foo:bar}`. Only how `foo` and how `bar` were parsed changed. Everywhere else, backslashes escape whatever follows, as they always have in version 1 of the parser. So your section snippet needs to be `\\section{section name}`, as it was before #226.

**Comment by CharlesGueunet** [comment]
Ok, so my bad. It should be an incompatibility with vim-snippets. I will
talk to them about that.
Thank you for your answer.
