### ISSUE TITLE
pug/jade new snippet

### ISSUE THREAD

**Issue by xavierartot** [garbas/vim-snipmate#237]
Hi there,
I have snippets for Pug/Jade with bootstrap too:
https://github.com/xavierartot/snippets/tree/master/ultinsnip
can you merge it.

**Comment by ajzafar** [comment]
Hi @xavierartot ! This repo no longer contains snippets. It'd be best to send these snippets towards the [honza/vim-snippets](https://github.com/honza/vim-snippets) repo. Thanks though!
