### ISSUE TITLE
How to make snippet description to show up

### ISSUE THREAD

**Issue by cricrazy** [garbas/vim-snipmate#238]
Hello, 

thank you for this amazing plugin. I am trying for description to show up for completion dialog. 

Here is my snippet. 

> snippet where where_statement
> 	WHERE(${1:condition}, ${2:count})
> 	
> 	IF ($2 GT 0) THEN BEGIN
> 	
> 	ENDIF
> snippet eof end_of file
> 	WHILE NOT EOF(UNIT) DO BEGIN
> 	
> 	ENDWHILE

When I press Ctrl+R+Tab, it only shows me WHERE and WHILE in the list but no description. 

Is the description for this reason, or am I mistaken? (I almost think it as a hint for you to remind you about that snippet).

Thank y'all.

**Comment by ajzafar** [comment]
I've added this in 3198619. As of right now the description in the pop up menu is the exact same as in the multisnip prompt. Having that in the pop up menu looks a little crowded, so I've made it disabled by default. To enable it, you need something like

    let g:snipMate = {}
    let g:snipMate.description_in_completion = 1

in your vimrc. In the future the way SnipMate stores descriptions will hopefully be a little cleaner, and descriptions may become default in completions.

Thanks for the suggestion!
