### ISSUE TITLE
Tab not working only on Typescript files

### ISSUE THREAD

**Issue by danazkari** [garbas/vim-snipmate#241]
Hello!
I'm using vim-snipmate with a whole other bunch of plugins so it could perfectly be my fault. But I do get this weird behavior ONLY on typescript files.

https://asciinema.org/a/6aewtb1eyg7l4054nfnolvx86

When I hit tab, the snippet key disappears and nothing else comes up.

If it makes any difference here's my config https://github.com/danazkari/vim-config

**Comment by ajzafar** [comment]
@danazkari I'm sorry I'm not able to reproduce this. Can you follow the steps in the FAQ and provide as much information about those steps as you can?

**Comment by jeroenvanagt** [comment]
I have exactly the same problem. I use vundle in my .vimrc file to load snipmate and snippets for typescript

Here is my .vimrc

```
"set nocompatible              " be iMproved, required
filetype off                  " required

syntax enable
colorscheme monokai
set wildignore+=*/node_modules/*
set hidden "Allow switching between modified buffers
set number
set laststatus=2

autocmd BufNewFile,BufRead *.ts setlocal filetype=typescript

"Set powerline
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'mileszs/ack.vim'
Plugin 'ddollar/nerdcommenter'
Plugin 'tomtom/tlib_vim'
Plugin 'marcweber/vim-addon-mw-utils'
Plugin 'magarcia/vim-angular2-snippets'
Plugin 'honza/vim-snippets'
Plugin 'garbas/vim-snipmate'
Plugin 'vim-scripts/ZoomWin'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'godlygeek/tabular'
Plugin 'christoomey/vim-system-copy'
Plugin 'vim-scripts/ReplaceWithRegister'
Plugin 'dsimidzija/vim-nerdtree-ignore'
Plugin 'mantiz/vim-plugin-dirsettings'
Plugin 'leafgarland/typescript-vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required



map <leader>n :NERDTreeToggle<CR>
```

When creating a new test.ts file vim recognizes the filetype as typescript. However, when I type ng2-component<TAB> the text ng2-component disappears and nothing happens.

I am using the following typescript snippets:
https://github.com/magarcia/vim-angular2-snippets

How to fix this?

**Comment by jeroenvanagt** [comment]
By the way, other snippets (like HTML) work fine.

**Comment by dapullar** [comment]
+1 have the exact same problem

**Comment by ajzafar** [comment]
If all of you are using magarcia/vim-angular2-snippets, then that's the problem. I'm not sure if they were intended for use with SnipMate, but they don't follow SnipMate's snippet syntax. The abbr lines should not be there, and all indentation should be done with hard tabs.
