### ISSUE TITLE
How to type multiple lines in a tab stop?

### ISSUE THREAD

**Issue by chaos5958** [garbas/vim-snipmate#243]
void test{
 {$1:test}
}$0

Suppose I want to write a snippet as above format.
I will write multiple lines in $1 with typing enters.
However, when I type a enter, my tab stop ends and I cannot go to $0 even though I type a tab.
How can I handle this issue?

Thanks, :)

**Comment by ajzafar** [comment]
This is currently unsupported. There is a very small chance it may be supported at some point in the future, but it won't be any time soon, if at all. Detecting changes in a placeholder and propagating them to all mirrors can be difficult as is with a placeholder on a single line. Supporting multiple lines complicates the problem quite a bit.

Instead I suggest rethinking how you write your snippets. The one you've provided for example should probably be something like:
    void test {
        ${0:test content}
    }
Then you'll leave the snippet as soon as you enter the body of the test, and you can create other snippets to employ there.
