### ISSUE TITLE
Cursor at the wrong place

### ISSUE THREAD

**Issue by AckslD** [garbas/vim-snipmate#244]
I have vim 7.4 on macOS 10.12.1. When I expand the following snippet

```
snippet eq equation environment
    \begin{equation}
        ${1:equation}
    \end{equation}
    ${0}
```

by typing `eq<Tab>` I get the correct code, that is

```
\begin{equation}
     equation
\end{equation}
```

but the cursor end up at the wrong place, the letters "\end{e" in the last row are marked in --SELECT-- mode. Any idea what the problem might be?

As another example, I have the following snippet:

```
snippet eqnarray eqnarray environment
    \begin{eqnarray}
        ${0:${VISUAL}}
    \end{eqnarray}

```
and when I expand I get

```
\begin{eqnarray}
    $
\end{eqnarray}
```

where the `\` before the end-statement is selected.

**Comment by ajzafar** [comment]
@AckslD Which version of the snippet parser are you using?

**Comment by AckslD** [comment]
When I open vim, `g:snipMate.snippet_version` is not set. But I've tried setting this to both 0 and 1 with the same result. Is this what you mean?
Thanks!

**Comment by AckslD** [comment]
I can't say why but it made a difference setting the version directly in my vimrc, rather than as a command. Now it actually works :)

**Comment by ajzafar** [comment]
@AcksID Are both issues fixed when you do that? I asked about the version because the way you used `${VISUAL}` is specific to version 1 (version 0 doesn't use the `$`, explaining why that shows up). The other issue of SnipMate selecting the wrong text I was hoping to look into today but haven't yet.

**Comment by AckslD** [comment]
Yes, both are solved! :)
Just let me know if you want more information, but both of the examples I had in my first post are now working. Although I had to change the backslashes to double backslashes.
Thanks!
