### ISSUE TITLE
latest snipmate broken with latest tlib

### ISSUE THREAD

**Issue by yann-morin-1998** [garbas/vim-snipmate#246]
Hello,

I just updated snipmate@2d70860ba49afc83cb5902acb99174e3cf08538d and tomtom/tlib_vim@b80c8f0f932ffaf9078f6998fe422cfbc7b95178, and snippets exansion is now broken:

    Error detected while processing /home/ymorin/.home/.vim/bundle/snipmate/autoload/snipMate.vim:
    line    9:
    you're missing tlib. See install instructions at /home/ymorin/.home/.vim/bundle/snipmate/README.md
    Press ENTER or type command to continue
    Error detected while processing /home/ymorin/.home/.vim/bundle/snipmate/autoload/snipMate.vim:
    line    9:
    you're missing tlib. See install instructions at /home/ymorin/.home/.vim/bundle/snipmate/README.md
    Press ENTER or type command to continue

I'm unsure whether to fill a bug in snipmate or tlib, so here it is in snipmate. ;-)

Regards,
Yann E. MORIN.

**Comment by ErichDonGubler** [comment]
I had this issue recently, and it was because of an out-of-date version of Vim -- what version/platform are you using?

**Comment by yann-morin-1998** [comment]
@ErichDonGubler I'm using vim 7.4 as packaged in Ubuntu 16.04 LTS, which can hardly be called an out-of-date vim version...

**Comment by ErichDonGubler** [comment]
@yann-morin-1998: I had Vim 7.4 also, though I didn't write down the version number. "out-of-date" might be a misnomer,, but whatever the case upgrading my version of Vim fixed it.

**Comment by ilyuha21st** [comment]
Yes, It looks like last tlib commit broke this. The workaround is to use latest tlib release (do not confuse with a latest commit :))

**Comment by vitosans** [comment]
I had to install it by hand, both vundle and the vba file wouldn't work. once I installed by hand it worked.

**Comment by yann-morin-1998** [comment]
This has been fixed in tlib with tomtom/tlib_vim@14ed720891d846c01278a6dd9e4f3d1cf2c4a660

Closing.
