### ISSUE TITLE
Feature: refresh `snippet_dirs` on events like an `rtp` change?

### ISSUE THREAD

**Issue by ErichDonGubler** [garbas/vim-snipmate#247]
I have an interesting situation where I would like project-specific snippets, which should be local to the project's source. I've considered trying something like [`exVim`](https://exvim.github.io/), but it seems a bit heavy-handed of a solution. I'm currently trying [`localvimrc`](https://github.com/embear/vim-localvimrc) in order to manipulate the `runtimepath` (AKA `rtp`), so I can get project-specific snippets.

Here's the structure I'm using right now:

```
- project
  - .vim
    + plugin
    + snippets (here's where we have some snippets I want to use!)
  * .lvimrc (points to `.vim` as a new `rtp` segment)

```

I'm able to get ...but I get no snippets for my project! What's happening?

After some digging, [from what I see in SnipMate's `plugin` folder](https://github.com/garbas/vim-snipmate/blob/master/plugin/snipMate.vim#L96) I need to manipulate the `runtimepath` BEFORE Snipmate's `plugin` folder is `runtime`'d. This approach works when I use `pathogen` to set/`runtime` my `rtp` up front, but subsequent edits to the `rtp` are missed by SnipMate because it only splits the `rtp` once. 

I'd strongly prefer to avoid any explicit calls to reload SnipMate's snippets from `rtp`, since that would couple my local `vimrc` to SnipMate (and we want to let others use their own simply replicating the `snippets` folder structure for the directory I add to `rtp`. Would it be possible to get a copy of `rtp` (probably implemented [here]()), and update the `snippet_dirs` accordingly when we notice it's changed (probably implemented [here](https://github.com/garbas/vim-snipmate/blob/master/autoload/snipMate.vim#L379))?

I'd be more than happy to do a PR, but I want to make sure that there's not a better way to do this or that this isn't something you'd be willing to support.

**Comment by ajzafar** [comment]
Done in f1432b6. Thanks!
