### ISSUE TITLE
Autocompletion/dropdown list for methods of a package with TAB?

### ISSUE THREAD

**Issue by heoa** [garbas/vim-snipmate#257]
Suppose I load different packages and I would like to get their methods. I type Prime::TAB where I want to get a dropdown list about methods, preferrably with autocompletion support.

Is this functionality possible to be turnt on or possible to be added in Vim-snipmate or is this available in some other package?

**Comment by ajzafar** [comment]
It sounds like you would benefit from a completion plugin like YouCompleteMe. Those will at least complete method names.

SnipMate currently doesn't offer completion like that. I have some ideas about implementing a simpler way for snippets to be generated for methods, based on MarcWeber's work, but I haven't had the time to work on SnipMate in a while. Hopefully that'll change in the next few weeks.

**Comment by heoa** [comment]
I tested YCM but it conflicts with my existing packages so removed it. This may be worth next try, to avoid such conflicts, http://www.vim.org/scripts/script.php?script_id=4433.
