### ISSUE TITLE
Problem about add current time in snippet（windows）

### ISSUE THREAD

**Issue by MoneySail** [garbas/vim-snipmate#266]
snippet date
`system("date +%Y-%m-%d")`

the two lines above work in linux, I don't know how to write the snippet in windows 7,
thank you! SOS!

**Comment by ajzafar** [comment]
@MoneySail If you haven't figured this out yet you can use the `date /t` command

    snippet date
        system("date /t")

There's more information available [via Google](https://www.google.com/search?q=windows+command+line+date), for [example](https://www.windows-commandline.com/get-date-time-batch-file/).
