### ISSUE TITLE
Markdown files doesn't work

### ISSUE THREAD

**Issue by Hund** [garbas/vim-snipmate#270]
The plugin works just fine for the other file types I've tried it with, just not with Markdown which is something I rely a lot on.

I have the file `markdown.snippets` in the folder `~/.vim/snippets/`where the other working snippet files are.

I'm running Vim 8.0.1298 with these plugins loaded using Vundle:

```
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
```

What to do?

**Comment by ajzafar** [comment]
@Hund Is this still happening for you? Can you go through the steps outlined in the FAQ? Thank you!

**Comment by Hund** [comment]
It's working now. :)
