### ISSUE TITLE
Possibility to disable snipMateVisual

### ISSUE THREAD

**Issue by wj-zhe** [garbas/vim-snipmate#271]
Wonder if it's possible to disable snipMateVisual function separately...

**Comment by ajzafar** [comment]
@wj-zhe Yeah absolutely! Just run `xunmap <Tab>`. Add this to a file in `~/.vim/after/plugin/` to make it permanent. Snippets can still use the visual tabstop `$VISUAL`, but it will just be replaced with nothing.
