### ISSUE TITLE
Snippet "pas.snippets" not work!

### ISSUE THREAD

**Issue by ivanalaman** [garbas/vim-snipmate#274]
Dears,

I created a file "pas.snippets" to work with file.pas, however, this snippet not work. Other snippets as R, Rnw, Html, work normally. 

Any suggestion?

**Comment by ajzafar** [comment]
@ivanalaman Can you go through the steps outlined in the FAQ? Thank you!

**Comment by ivanalaman** [comment]
My operating system is debian buster.
I'm using the vim editor version 8.1.1401.
I installed the referred plugin, and created a snipett in the ./vim/plugged/vim-snippets/snippets/pas.snippets folder with the following code:

snippet begin
             begin
             $ {0}
             end.
snippet writeln
             writeln ($ {0});

When I open my hello.pas file and try to fire the command as a begin + tab trigger nothing happens.

Do you need any more information?

**Comment by ivanalaman** [comment]
I found the solution in topic "Not detecting `.eex` files in order to associate with `eelixir` snippets #261." Putting it ":se filetype"  I found that the correct snippet would be "freepascal.snippets". Thank you!
