### ISSUE TITLE
Placeholder with Mirrors and Evaluations is broken

### ISSUE THREAD

**Issue by ditodidio** [garbas/vim-snipmate#278]
I copied the following from the Snipmate manual, just to give it a try. But that feature seems to be completly broken in the current master.

Finally, placeholders can contain mirrors and evaluations (detailed below) and   
even entire other tab stops. If the placeholder is edited, then these nested     
tab stops are removed and skipped entirely. For example, 
```
    snippet div                                                                  
        <div${1: id="${2:id}"}${3: class="${4:class}"}>                          
            $0                                                                   
        </div>
```

If i use this snippet in my code. It does not work. The snippet expands but the selection of the first attribute is incorrect and if i tab again the cursor jumps to the end of the snippet, not to the next tabstop.

the first selection looks like that (from * to * ):

```
<div* id="${2:id*"} class="${4:class"}> 
                          
</div>
```

**Comment by ajzafar** [comment]
Unfortunately I'm not able to reproduce this. Could you please go through the following steps to try and diagnose this?

* What Vim version are you on? Are you on master of SnipMate?
* Can you try disabling other plugins individually and see if the problem persists?
* Can you share your vimrc and any other personal settings you use?
* Alternatively could you work from the other end: try creating a minimal vimrc with minimal plugins to recreate the issue?

**Comment by ditodidio** [comment]
So i removed nearly all my plugins and reduced my vimrc file and it still does not work.

Vim Version: 7.4.1689 und 8.0.586
Snipmate: master

Plugins: 
tlib_vim-master/  [https://github.com/tomtom/tlib_vim/commit/a071b6d41b20069a3520e0d101194a752968973b](url)      aktueller Master   
vim-snipmate/ [https://github.com/garbas/vim-snipmate/commit/68eebf9dabe5c1d1964e78dda188765f224bab34](url) Master
vim-addon-mw-utils-master/  [https://github.com/MarcWeber/vim-addon-mw-utils/commit/6aaf4fee472db7cbec6d2c8eea69fdf3a8f8a75d](url) aktueller master
vim-snippets-master/ [https://github.com/honza/vim-snippets/commit/6159e8e820656e4370d54ddbf11278bf92794139](url) aktueller Master

```
execute pathogen#infect()
call pathogen#helptags()
filetype on
syntax on
filetype plugin on
imap <TAB> <Plug>snipMateNextOrTrigger
smap <TAB> <Plug>snipMateNextOrTrigger
```

**Comment by ajzafar** [comment]
So I figured out the issue. Nested placeholders are only supported in version 1 of the snippet parser. To use that version either add a line that says `version 1` to the beginning of your `.snippets` files or add the following to your vimrc:
```
let g:snipMate = {}
let g:snipMate.snippet_version = 1
```

This wasn't documented very well such that even I forgot. I'm sorry for that. I've updated the documentation. I think it's also time to deprecate version 0 of the snippet parser. This is a great feature, and I'm sure there are many out there still using the old parser. I will do that this weekend at the latest.

**Comment by ajzafar** [comment]
Alright I'm a couple days late, but the process begins now. There'll be a message about the switch to users at first, and then the default will change to the new version. Later on the line we'll remove the legacy parser, and precede that with a message to users of that parser.

**Comment by ditodidio** [comment]
I think it would be enough to document that this feature does not work with parser version 0. It works with version 1. Maybe you could keep everything in place and just make the new parser version the default.

**Comment by ajzafar** [comment]
I don't want to switch the default and break things for current users, so I'm going for a transition process. Version 0 is deprecated as of today, but it will still remain in SnipMate for a very long time, especially given the current pace of SnipMate development.

**Comment by specious** [comment]
Perhaps it's better to make version 1 the default, but have it show a message that you can set it back to 0?
