### ISSUE TITLE
Undefined variable: g:snipMate

### ISSUE THREAD

**Issue by mcastorina** [garbas/vim-snipmate#279]
Following the deprecation warning, I added the following to my `.vimrc`.

```
let g:snipMate.snippet_version = 1
```

But when I start vim I still get the deprecation message plus an "undefined variable" message.

```
E121: Undefined variable: g:snipMate
The legacy SnipMate parser is deprecated. Please see :h SnipMate-deprecate.
```

**Comment by mcastorina** [comment]
I got it working with

```
let g:snipMate = {'snippet_version': 1}
```

Maybe update the help message? Anyway, thanks for the great plugin!

**Comment by ajzafar** [comment]
Message is updated. Thanks for the idea and for using SnipMate!
