### ISSUE TITLE
How do I write a snippet file which applies for all filetypes?

### ISSUE THREAD

**Issue by justrajdeep** [garbas/vim-snipmate#288]
Hi 

I understand that we can create snippet files with `<filetype>.snippet` syntax. But how do I write a snippet that apples to all file types?

Thanks in advance :)

**Comment by ajzafar** [comment]
@justrajdeep Any snippets in the `_` scope will be loaded for all filetypes. For example, snippets placed in a file named `_.snippets`.

Apparently this is not documented anywhere, so I'll add that. Thanks for pointing that out indirectly!

**Comment by justrajdeep** [comment]
Thanks
