### ISSUE TITLE
jump to placeholders not reliable

### ISSUE THREAD

**Issue by laoshaw** [garbas/vim-snipmate#291]
I set my jump keyword to ;; 

sometimes it jumps sometimes it does not, not sure why

is there a setting of delay between the jump so I can make it longer?

**Comment by ajzafar** [comment]
@laoshaw Using maps of multiple, printable characters is doable, but there are some necessary implications, which you can read about at `:h map-ambiguous`, `:h :map-nowait`, and `:h map-typing`. That last one points you at the options you're looking for.

I'm going to close this, but  feel free to ask more questions here if you have them after reading those help entries.
