### ISSUE TITLE
 Install with Pathogen/Vundle unnecessary in Vim 8+

### ISSUE THREAD

**Issue by h3xx** [garbas/vim-snipmate#297]
Ever since Vim 8 (released 2016-09-12), it's supported plugin directories natively in `~/.vim/pack/*/start/<plugin>`.

For example:

```sh
mkdir -p ~/.vim/pack/my-ruby-stuff/start
git clone https://github.com/tpope/vim-rails ~/.vim/pack/my-ruby-stuff/start/vim-rails
```

This is sufficient to install the plugin on Vim 8.0 and later. No Pathogen or Vundle intervention is necessary whatsoever.

The installation instructions in this and other long-running projects have been the same since forever, suggesting now-obsolete things like Vundle or Pathogen. It's like the maintainers don't know about this feature of Vim. So, I'm just letting you know.

**Comment by ajzafar** [comment]
@h3xx Wow thank you for that information! I haven't been following Vim development as closely as I used to and completely missed it. I'm going to leave this open in a tab until I have time to update the instructions.

Thanks again!

**Comment by ajzafar** [comment]
New instructions added! Thanks again for pointing them out!
