### ISSUE TITLE
(Feature Request) Support for giving definitions priority

### ISSUE THREAD

**Issue by phillipberndt** [garbas/vim-snipmate#36]
See
 http://code.google.com/p/snipmate/issues/detail?id=73#

With your code, the script does not throw an error message anymore but it still forces users to pick the desired expansion from a list. I'd like to be able to declare my definition as "the important one" which is extended automatically without any inquiries.

I implemented the suggestion from the bug report at Google code, i.e. the "snippet!" command, for msander's code base
 https://github.com/msanders/snipmate.vim/pull/30
but I found that it is incompatible with the way you manage the snippets.

Here is a simple idea how one could do this here:
 https://github.com/phillipberndt/vim-snipmate/commit/8192668d3225e939cedbe523fe6f67ca6b55223f

**Comment by ajzafar** [comment]
It's merged.

**Comment by baskerville** [comment]
It doesn't seem to work. If `~/.vim/snippets/html.snippets` contains:
```
snippet! head
	foo
```
Loading an HTML file will produce the following error:
```
Error detected while processing function GetSnippets..<SNR>28_DefineSnips..ExtractSnipsFile..MakeSnip:
line    5:
E713: Cannot use empty key for Dictionary
```

**Comment by ajzafar** [comment]
@baskerville It looks like you're using an older version of SnipMate (or perhaps the original msanders repo instead of this repo). The function `MakeSnip` mentioned in your error message does not exist in this repo. Please make sure you're using the garbas repo and updated to master. If you're still getting an error, please open a new, separate issue.

**Comment by baskerville** [comment]
I was indeed using the old repo. It works as expected when the snippets live in `~/.vim/after/snippets`. Thanks.
