### ISSUE TITLE
Debugging Key Not Present In Dictionary: get_snippets

### ISSUE THREAD

**Issue by jackkinsella** [garbas/vim-snipmate#41]
I'm having trouble getting snipMate working alongside SuperTab. In fact it's the only feature in Textmate which I still cannot replicate in VIM.

I'm sure I'm not alone. 

Janus (https://github.com/carlhuda/janus), a MacVim distro with over 2000 watchers on Github, includes both plugins yet only SuperTab works. By default Janus uses the unmaintained msanders repo but I configured it to use yours instead. Now, whenever I press Tab I get the error above. Equally, pressing <pre><code> < c-r >< tab > </code></pre> gives a similar error.

Have you any ideas on how to debug this? Better yet would be assistance in updating Janus so that snipMate and SuperTab work side by side once and for, happily ever after.

**Comment by arcseldon** [comment]
For my situation, the problem was having `supertab` plugin also enabled. There are some incompatibilities.
