### ISSUE TITLE
Defaulting value to another value bug

### ISSUE THREAD

**Issue by bogdan** [garbas/vim-snipmate#59]
Let's say we have the following skippet:

k.snippet:

```
:${1:} => ${2:$1}
```

Key sequence: `ik<Tab>hello<Tab>` should:

* enter insert mode
* expand the snippet 
* fill in first value
* set second value default to first value 
* highlight second value, but it is not

**Comment by ajzafar** [comment]
This seems to have been fixed along with the work on allowing nested stops.

**Note**: This is only fixed for `g:snipMate.snippet_version = 1`.
