### ISSUE TITLE
"self" from dot "." in python snippet problematic

### ISSUE THREAD

**Issue by schivmeister** [garbas/vim-snipmate#65]
When used for eg. with SuperTab for context-based completion, everything is fine except for:

math.<tab> == mathself.
math.<tab><tab> == mathselfself.

It would be better if the completion here could be context-aware, so for eg. in Python we want "." to expand to "self" only when there is nothing before it, so we could have "something." and not "somethingself."

**Comment by fvisin** [comment]
+1 I would also like this option implemented in the original snipmate.

My solution for the time being is to fork https://github.com/honza/snipmate-snippets and remove the `.` snippet. The best for me would be to have an configuration option in snipmate to ignore some snippets. Do you think it could be feasible?

**Comment by ajzafar** [comment]
@fvisin I've moved your request to a new issue, #214.

**Comment by ajzafar** [comment]
I've always viewed this as a clash of expectations between SnipMate and users. To me this was a question of what is an allowable trigger? I think this still asks that question, but in looking at SnipMate again the past few days, I came up with a solution that I've just pushed in c318076.

The fundamental problem here is that SnipMate thinks `.` is a potential trigger here. Why wouldn't it? There's a `.` right at the end there. As the user, you can tell that the `.` trigger already expanded to `self.`, so why can't we just tell SnipMate that? Now you can.

The [added documentation](https://github.com/garbas/vim-snipmate/blob/c318076739392bc65ba0f11a9ef88daf38357ecb/doc/SnipMate.txt#L235) includes an example that solves exactly this issue. It works by allowing SnipMate to create its normal list of triggers, and then, if `self.` is before the cursor, it removes the `.` as a possible trigger, and lets SnipMate continue on its way. Thus no never-ending `selfselfself.`

This is the first autocommand I've introduced, and I doubt it'll be the last. Over time there may be better ways of accomplishing this than the one I've just presented. But I'm still marking this one solved.

If you have any problems with the autocommand, please open a new issue. If you're having trouble specifically with a snippet that ends with its own trigger like in OP's case, please reopen this.

Thank you!

**Comment by davidhalter** [comment]
Thanks for looking into this 12 years later. One of the reasons why I love open source :heart:
